<?php
// Catalogo extraido integralmente de Database::seedPhoneModels().
return [
            'Apple' => [
                'iPhone 7', 'iPhone 7 Plus', 'iPhone 8', 'iPhone 8 Plus', 'iPhone X', 'iPhone XR',
                'iPhone XS', 'iPhone XS Max', 'iPhone 11', 'iPhone 11 Pro', 'iPhone 11 Pro Max',
                'iPhone 12', 'iPhone 12 Mini', 'iPhone 12 Pro', 'iPhone 12 Pro Max',
                'iPhone 13', 'iPhone 13 Mini', 'iPhone 13 Pro', 'iPhone 13 Pro Max',
                'iPhone 14', 'iPhone 14 Plus', 'iPhone 14 Pro', 'iPhone 14 Pro Max',
                'iPhone 15', 'iPhone 15 Plus', 'iPhone 15 Pro', 'iPhone 15 Pro Max',
                'iPhone 16', 'iPhone 16 Plus', 'iPhone 16 Pro', 'iPhone 16 Pro Max',
                'iPhone 16e', 'iPhone 17', 'iPhone 17 Pro', 'iPhone 17 Pro Max',
                'iPhone 17e', 'iPhone Air',
            ],
            'Samsung' => [
                'Galaxy Core', 'Galaxy Core 2', 'Galaxy Core Prime', 'Galaxy Grand Prime',
                'Galaxy Grand Prime Duos', 'Galaxy Gran Prime', 'Galaxy J1', 'Galaxy J1 Ace',
                'Galaxy J1 Mini', 'Galaxy J1 Mini Prime', 'Galaxy J2', 'Galaxy J2 Core',
                'Galaxy J2 Prime', 'Galaxy J2 Pro', 'Galaxy J3', 'Galaxy J3 Prime',
                'Galaxy J4', 'Galaxy J4 Core', 'Galaxy J4 Plus', 'Galaxy J5',
                'Galaxy J5 Metal', 'Galaxy J5 Prime', 'Galaxy J5 Pro', 'Galaxy J6',
                'Galaxy J6 Plus', 'Galaxy J7', 'Galaxy J7 Duo', 'Galaxy J7 Metal',
                'Galaxy J7 Neo', 'Galaxy J7 Prime', 'Galaxy J7 Prime 2', 'Galaxy J7 Pro',
                'Galaxy J8', 'Galaxy On5', 'Galaxy On7',
                'Galaxy A3', 'Galaxy A5', 'Galaxy A6', 'Galaxy A6 Plus', 'Galaxy A7',
                'Galaxy A8', 'Galaxy A8 Plus', 'Galaxy A9', 'Galaxy A9 Pro',
                'Galaxy A01', 'Galaxy A02', 'Galaxy A02s', 'Galaxy A03', 'Galaxy A03 Core',
                'Galaxy A03s', 'Galaxy A04', 'Galaxy A04e', 'Galaxy A04s', 'Galaxy A05',
                'Galaxy A05s', 'Galaxy A06', 'Galaxy A06 5G', 'Galaxy A10', 'Galaxy A10s',
                'Galaxy A11', 'Galaxy A12', 'Galaxy A13', 'Galaxy A14', 'Galaxy A14 5G',
                'Galaxy A15', 'Galaxy A15 5G', 'Galaxy A16', 'Galaxy A16 5G', 'Galaxy A20',
                'Galaxy A20s', 'Galaxy A21s', 'Galaxy A22', 'Galaxy A22 5G', 'Galaxy A23',
                'Galaxy A23 5G', 'Galaxy A24', 'Galaxy A25', 'Galaxy A26 5G', 'Galaxy A30',
                'Galaxy A30s', 'Galaxy A31', 'Galaxy A32', 'Galaxy A32 5G', 'Galaxy A33',
                'Galaxy A34', 'Galaxy A35', 'Galaxy A36 5G', 'Galaxy A50', 'Galaxy A50s',
                'Galaxy A51', 'Galaxy A52', 'Galaxy A52s', 'Galaxy A53', 'Galaxy A54',
                'Galaxy A55', 'Galaxy A56 5G', 'Galaxy A70', 'Galaxy A71', 'Galaxy A72',
                'Galaxy A73', 'Galaxy A80', 'Galaxy M12', 'Galaxy M13', 'Galaxy M14',
                'Galaxy M15', 'Galaxy M21', 'Galaxy M22', 'Galaxy M23', 'Galaxy M31',
                'Galaxy M31s', 'Galaxy M32', 'Galaxy M33', 'Galaxy M34', 'Galaxy M35',
                'Galaxy M51', 'Galaxy M52', 'Galaxy M53', 'Galaxy M54', 'Galaxy M55',
                'Galaxy F12', 'Galaxy F13', 'Galaxy F14', 'Galaxy F23', 'Galaxy F34',
                'Galaxy S6', 'Galaxy S6 Edge', 'Galaxy S6 Edge Plus', 'Galaxy S7',
                'Galaxy S7 Edge', 'Galaxy S8', 'Galaxy S8 Plus',
                'Galaxy S9', 'Galaxy S9 Plus', 'Galaxy S10', 'Galaxy S10 Plus', 'Galaxy S10e',
                'Galaxy S20', 'Galaxy S20 Plus', 'Galaxy S20 Ultra', 'Galaxy S20 FE',
                'Galaxy S21', 'Galaxy S21 Plus', 'Galaxy S21 Ultra', 'Galaxy S21 FE',
                'Galaxy S22', 'Galaxy S22 Plus', 'Galaxy S22 Ultra', 'Galaxy S23',
                'Galaxy S23 Plus', 'Galaxy S23 Ultra', 'Galaxy S23 FE', 'Galaxy S24',
                'Galaxy S24 Plus', 'Galaxy S24 Ultra', 'Galaxy S24 FE', 'Galaxy S25',
                'Galaxy S25 Plus', 'Galaxy S25 Ultra', 'Galaxy Note 8', 'Galaxy Note 9',
                'Galaxy Note 10', 'Galaxy Note 10 Plus', 'Galaxy Note 20', 'Galaxy Note 20 Ultra',
                'Galaxy Z Flip', 'Galaxy Z Flip 3', 'Galaxy Z Flip 4', 'Galaxy Z Flip 5',
                'Galaxy Z Flip 6', 'Galaxy Z Fold 2', 'Galaxy Z Fold 3', 'Galaxy Z Fold 4',
                'Galaxy Z Fold 5', 'Galaxy Z Fold 6',
            ],
            'Motorola' => [
                'Moto C', 'Moto C Plus', 'Moto E', 'Moto E2', 'Moto E3', 'Moto E3 Power',
                'Moto E4', 'Moto E4 Plus', 'Moto E4 Play',
                'Moto E5', 'Moto E5 Plus', 'Moto E6', 'Moto E6 Play', 'Moto E6 Plus',
                'Moto E5 Play', 'Moto E6i', 'Moto E6s', 'Moto E7', 'Moto E7 Plus',
                'Moto E7 Power', 'Moto E13',
                'Moto E14', 'Moto E20', 'Moto E22', 'Moto E22i', 'Moto E30', 'Moto E32',
                'Moto E32s', 'Moto E40', 'Moto G', 'Moto G2', 'Moto G3',
                'Moto G4', 'Moto G4 Plus', 'Moto G4 Play', 'Moto G5', 'Moto G5 Plus', 'Moto G5s',
                'Moto G5s Plus', 'Moto G6', 'Moto G6 Plus', 'Moto G6 Play', 'Moto G7',
                'Moto G7 Plus', 'Moto G7 Play', 'Moto G7 Power', 'Moto G8',
                'Moto G8 Plus', 'Moto G8 Play', 'Moto G8 Power', 'Moto G9',
                'Moto G9 Plus', 'Moto G9 Play', 'Moto G9 Power', 'Moto G10',
                'Moto G10 Power', 'Moto G14', 'Moto G15', 'Moto G20', 'Moto G22',
                'Moto G23', 'Moto G24', 'Moto G24 Power', 'Moto G30', 'Moto G31',
                'Moto G32', 'Moto G34 5G', 'Moto G35 5G', 'Moto G41', 'Moto G42',
                'Moto G50', 'Moto G51', 'Moto G52', 'Moto G53', 'Moto G54',
                'Moto G55', 'Moto G60', 'Moto G62', 'Moto G71', 'Moto G72',
                'Moto G73', 'Moto G82', 'Moto G84', 'Moto G85', 'Moto G100',
                'Moto G200', 'Moto X4', 'Moto Z', 'Moto Z Play', 'Moto Z2 Force',
                'Moto Z2 Play', 'Moto Z3 Play', 'Motorola One', 'Motorola One Action',
                'Motorola One Fusion', 'Motorola One Fusion Plus', 'Motorola One Hyper',
                'Motorola One Macro', 'Motorola One Vision', 'Motorola One Zoom',
                'Motorola Edge', 'Motorola Edge Plus', 'Motorola Edge 20', 'Motorola Edge 20 Lite',
                'Motorola Edge 20 Pro', 'Motorola Edge 30', 'Motorola Edge 30 Fusion',
                'Motorola Edge 30 Neo', 'Motorola Edge 30 Pro', 'Motorola Edge 30 Ultra',
                'Motorola Edge 40', 'Motorola Edge 40 Neo', 'Motorola Edge 40 Pro',
                'Motorola Edge 50', 'Motorola Edge 50 Fusion', 'Motorola Edge 50 Neo',
                'Motorola Edge 50 Pro', 'Motorola Edge 50 Ultra',
                'Motorola Edge 60', 'Motorola Edge 60 Fusion', 'Motorola Edge 60 Neo',
                'Motorola Edge 60 Pro', 'Motorola Razr 40', 'Motorola Razr 40 Ultra',
                'Motorola Razr 50', 'Motorola Razr 50 Ultra',
            ],
            'Xiaomi' => [
                'Redmi 4', 'Redmi 4A', 'Redmi 4X', 'Redmi 5', 'Redmi 5 Plus',
                'Redmi 5A', 'Redmi 6', 'Redmi 6 Pro', 'Redmi 6A', 'Redmi 7',
                'Redmi 7A', 'Redmi 8', 'Redmi 8A', 'Redmi 8A Pro', 'Redmi 9',
                'Redmi 9 Prime', 'Redmi 9A', 'Redmi 9C', 'Redmi 9T',
                'Redmi 10', 'Redmi 10A', 'Redmi 10C', 'Redmi 11 Prime', 'Redmi 12',
                'Redmi 12 5G', 'Redmi 12C', 'Redmi 13', 'Redmi 13C', 'Redmi 14C',
                'Redmi Go', 'Redmi S2', 'Redmi Note 4', 'Redmi Note 4X', 'Redmi Note 5',
                'Redmi Note 5 Pro', 'Redmi Note 6 Pro', 'Redmi Note 7', 'Redmi Note 7 Pro',
                'Redmi Note 8', 'Redmi Note 8 Pro', 'Redmi Note 9', 'Redmi Note 9 Pro',
                'Redmi Note 9S', 'Redmi Note 10', 'Redmi Note 10 5G', 'Redmi Note 10 Pro',
                'Redmi Note 10S', 'Redmi Note 11', 'Redmi Note 11 Pro',
                'Redmi Note 11 Pro 5G', 'Redmi Note 11S', 'Redmi Note 12',
                'Redmi Note 12 5G', 'Redmi Note 12 Pro', 'Redmi Note 12 Pro 5G',
                'Redmi Note 12 Pro Plus 5G', 'Redmi Note 12S', 'Redmi Note 13',
                'Redmi Note 13 5G', 'Redmi Note 13 Pro', 'Redmi Note 13 Pro 5G',
                'Redmi Note 13 Pro Plus 5G', 'Redmi Note 14', 'Redmi Note 14 5G',
                'Redmi Note 14 Pro 5G', 'Redmi Note 14 Pro Plus 5G', 'Pocophone F1',
                'Poco C3', 'Poco C31', 'Poco C40',
                'Poco C65', 'Poco C75', 'Poco F2 Pro', 'Poco F3', 'Poco F4', 'Poco F5',
                'Poco F5 Pro', 'Poco F6', 'Poco F6 Pro', 'Poco M3', 'Poco M4 Pro',
                'Poco M3 Pro 5G', 'Poco M4 Pro 5G', 'Poco M5', 'Poco M5s',
                'Poco M6', 'Poco M6 Pro', 'Poco X2', 'Poco X3',
                'Poco X3 NFC', 'Poco X3 Pro', 'Poco X4 Pro', 'Poco X5', 'Poco X5 Pro',
                'Poco X6', 'Poco X6 Pro', 'Poco X7', 'Poco X7 Pro',
                'Mi A1', 'Mi A2', 'Mi A2 Lite', 'Mi A3', 'Mi 6', 'Mi 8',
                'Mi 8 Lite', 'Mi 9', 'Mi 9 Lite', 'Mi 9 SE', 'Mi 9T', 'Mi 9T Pro',
                'Mi 10', 'Mi 10 Lite', 'Mi 10T', 'Mi 10T Lite', 'Mi 10T Pro',
                'Mi 11', 'Mi 11 Lite', 'Mi 11T', 'Mi 11T Pro', 'Xiaomi 11 Lite 5G NE',
                'Xiaomi 12', 'Xiaomi 12 Lite', 'Xiaomi 12T', 'Xiaomi 12T Pro',
                'Xiaomi 13', 'Xiaomi 13 Lite', 'Xiaomi 13T', 'Xiaomi 13T Pro',
                'Xiaomi 14', 'Xiaomi 14T', 'Xiaomi 14T Pro', 'Xiaomi 15',
            ],
            'LG' => ['K10', 'K11', 'K12', 'K22', 'K41S', 'K50S', 'K51S', 'K61', 'Q6', 'Q7', 'Velvet'],
            'Asus' => ['Zenfone 4', 'Zenfone 5', 'Zenfone 6', 'Zenfone 8', 'Zenfone 9', 'ROG Phone 5', 'ROG Phone 6'],
            'Realme' => ['Realme C11', 'Realme C21Y', 'Realme C25Y', 'Realme C35', 'Realme 7', 'Realme 8', 'Realme 9', 'Realme 10'],
            'Huawei' => ['P20 Lite', 'P30 Lite', 'P40 Lite', 'Y6', 'Y7', 'Y9', 'Nova 5T'],
            'Nokia' => ['Nokia 2.4', 'Nokia 3.4', 'Nokia 5.4', 'Nokia G10', 'Nokia G20', 'Nokia C20'],
            'Positivo' => ['Twist 3', 'Twist 4', 'Twist 5', 'Twist Tab'],
            'Multilaser' => ['MS50', 'MS60', 'G Max', 'G Pro'],
        ];

