<?php
$base=dirname(__DIR__);require $base.'/app/Config/App.php';require $base.'/app/Support/helpers.php';\App\Config\App::loadEnv($base);spl_autoload_register(function($c)use($base){if(str_starts_with($c,'App\\')){$f=$base.'/app/'.str_replace('\\','/',substr($c,4)).'.php';if(is_file($f))require $f;}});
$db=\App\Config\Database::getInstance();$prefix='TESTE_DEVICE_SECRET_';$run=bin2hex(random_bytes(4));$key=base64_encode(random_bytes(32));putenv('DEVICE_SECRET_KEY='.$key);$_ENV['DEVICE_SECRET_KEY']=$key;$port=18766;$cookieName=(string)app_env('SESSION_NAME','conectados_session');$ids=[];$fail=[];$ok=function($v,$m)use(&$fail){if(!$v)$fail[]=$m;};
$session=function($user,$profile)use($cookieName){$id=bin2hex(random_bytes(16));$csrf=bin2hex(random_bytes(32));session_name($cookieName);session_id($id);session_start();$_SESSION=['usuario_id'=>$user,'perfil'=>$profile,'_csrf_token'=>$csrf,'_last_activity'=>time()];session_write_close();return ['id'=>$id,'csrf'=>$csrf];};
$request=function($method,$route,$data,$sid)use($port,$cookieName){$url='http://127.0.0.1:'.$port.'/index.php?url='.rawurlencode($route);if($method==='GET'&&$data)$url.='&'.http_build_query($data);$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_COOKIE=>$cookieName.'='.$sid,CURLOPT_POSTFIELDS=>$method==='POST'?http_build_query($data):null,CURLOPT_TIMEOUT=>15]);$raw=(string)curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$hs=(int)curl_getinfo($ch,CURLINFO_HEADER_SIZE);curl_close($ch);return ['status'=>$status,'body'=>substr($raw,$hs)];};
$extract=function($html,$name){return preg_match('/name=["\']'.preg_quote($name,'/').'["\'][^>]*value=["\']([^"\']*)/i',$html,$m)?html_entity_decode($m[1],ENT_QUOTES):'';};
$cmd=[PHP_BINARY,'-d','extension=sodium','-S','127.0.0.1:'.$port,'-t',$base.'/public',$base.'/public/index.php'];$proc=proc_open($cmd,[1=>['pipe','w'],2=>['pipe','w']],$pipes,$base);
try{
 foreach([['admin','Administrador'],['unauthorized','Financeiro']] as [$k,$p]){$db->prepare("INSERT INTO usuarios(nome,email,senha,perfil,status) VALUES(:n,:e,:s,:p,'Ativo')")->execute([':n'=>$prefix.$run.$k,':e'=>strtolower($prefix.$run.$k).'@example.invalid',':s'=>password_hash(random_bytes(16),PASSWORD_BCRYPT),':p'=>$p]);$ids[$k]=(int)$db->lastInsertId();}$db->prepare('INSERT INTO clientes(nome,cpf_cnpj) VALUES(:n,:d)')->execute([':n'=>$prefix.$run,':d'=>'DS'.$run]);$ids['client']=(int)$db->lastInsertId();$admin=$session($ids['admin'],'Administrador');$unauthorized=$session($ids['unauthorized'],'Financeiro');
 $ready=false;for($i=0;$i<30;$i++){usleep(100000);$r=$request('GET','login',[],$admin['id']);if($r['status']>0){$ready=true;break;}}$ok($ready,'servidor local');
 $page=$request('GET','os/create',[],$admin['id']);$csrf=$extract($page['body'],'_csrf_token');$operation=$extract($page['body'],'os_create_operation_id');$nonce=$extract($page['body'],'os_create_payment_nonce');$secret=$prefix.'PIN_7391';
 $post=['_csrf_token'=>$csrf,'os_create_operation_id'=>$operation,'os_create_payment_nonce'=>$nonce,'cliente_id'=>$ids['client'],'marca'=>'Teste','modelo'=>$prefix.$run,'imei'=>'','cor'=>'','senha_padrao'=>$secret,'estado_fisico'=>$prefix,'problema_relatado'=>$prefix.$run,'prioridade'=>'Normal','tecnico_id'=>'','prazo_estimado'=>'','valor_mao_obra'=>'0','valor_pecas'=>'0','pagamento_inicial_valor'=>''];$request('POST','os/store',$post,$admin['id']);$stmt=$db->prepare('SELECT os.id,os.aparelho_id,a.senha_padrao FROM ordens_servico os JOIN aparelhos a ON a.id=os.aparelho_id WHERE os.problema_relatado=:p');$stmt->execute([':p'=>$prefix.$run]);$row=$stmt->fetch(PDO::FETCH_ASSOC);$ids['os']=(int)$row['id'];$ids['device']=(int)$row['aparelho_id'];$stored=(string)$row['senha_padrao'];$service=new \App\Services\DeviceSecretService($key);$ok($stored!==$secret&&$service->decrypt($stored)===$secret,'criacao HTTP criptografada');
 $view=$request('GET','os/viewDetail',['id'=>$ids['os']],$admin['id']);$ok($view['status']===200&&str_contains($view['body'],$secret)&&!str_contains($view['body'],$stored),'visualizacao autorizada');$list=$request('GET','os',[],$admin['id']);$print=$request('GET','os/print',['id'=>$ids['os']],$admin['id']);$ok(!str_contains($list['body'],$secret)&&!str_contains($list['body'],$stored)&&!str_contains($print['body'],$secret)&&!str_contains($print['body'],$stored),'lista/impressao sem segredo');$denied=$request('GET','os/viewDetail',['id'=>$ids['os']],$unauthorized['id']);$ok($denied['status']===403&&!str_contains($denied['body'],$secret)&&!str_contains($denied['body'],$stored),'usuario sem permissao');
 $edit=$request('GET','os/edit',['id'=>$ids['os']],$admin['id']);$ok(!str_contains($edit['body'],$secret)&&!str_contains($edit['body'],$stored)&&str_contains($edit['body'],'Deixe em branco para manter'),'edicao vazia');$editPost=['_csrf_token'=>$extract($edit['body'],'_csrf_token'),'id'=>$ids['os'],'payment_nonce'=>$extract($edit['body'],'payment_nonce'),'marca'=>'Teste','modelo'=>$prefix.$run,'imei'=>'','cor'=>'','senha_padrao'=>'','estado_fisico'=>$prefix,'status'=>'Recebido','prioridade'=>'Normal','tecnico_id'=>'','diagnostico_tecnico'=>'','servico_realizar'=>'','valor_mao_obra'=>'0','valor_pecas'=>'0','desconto'=>'0','prazo_estimado'=>'','forma_pagamento'=>'','pagamento_valor'=>''];$request('POST','os/update',$editPost,$admin['id']);$ok((string)$db->query('SELECT senha_padrao FROM aparelhos WHERE id='.$ids['device'])->fetchColumn()===$stored,'HTTP vazio preserva');
 $edit=$request('GET','os/edit',['id'=>$ids['os']],$admin['id']);$editPost['_csrf_token']=$extract($edit['body'],'_csrf_token');$editPost['payment_nonce']=$extract($edit['body'],'payment_nonce');$editPost['senha_padrao']='NOVO-2580';$request('POST','os/update',$editPost,$admin['id']);$new=(string)$db->query('SELECT senha_padrao FROM aparelhos WHERE id='.$ids['device'])->fetchColumn();$ok($new!==$stored&&$service->decrypt($new)==='NOVO-2580','HTTP substitui');
 $edit=$request('GET','os/edit',['id'=>$ids['os']],$admin['id']);$editPost['_csrf_token']=$extract($edit['body'],'_csrf_token');$editPost['payment_nonce']=$extract($edit['body'],'payment_nonce');$editPost['senha_padrao']='';$editPost['remover_senha_padrao']='1';$request('POST','os/update',$editPost,$admin['id']);$ok((string)$db->query('SELECT senha_padrao FROM aparelhos WHERE id='.$ids['device'])->fetchColumn()==='','HTTP remove');
}catch(Throwable $e){$fail[]=get_class($e).': '.$e->getMessage();}finally{if(is_resource($proc)){proc_terminate($proc);foreach($pipes as $pipe)fclose($pipe);proc_close($proc);}if(!empty($ids['os'])){foreach(['financeiro','os_pagamentos','os_historico'] as $t)$db->prepare("DELETE FROM $t WHERE os_id=:id")->execute([':id'=>$ids['os']]);$db->prepare('DELETE FROM ordens_servico WHERE id=:id')->execute([':id'=>$ids['os']]);}if(!empty($ids['device']))$db->prepare('DELETE FROM aparelhos WHERE id=:id')->execute([':id'=>$ids['device']]);if(!empty($ids['client']))$db->prepare('DELETE FROM clientes WHERE id=:id')->execute([':id'=>$ids['client']]);foreach(['admin','unauthorized'] as $k)if(!empty($ids[$k]))$db->prepare('DELETE FROM usuarios WHERE id=:id')->execute([':id'=>$ids[$k]]);putenv('DEVICE_SECRET_KEY');unset($_ENV['DEVICE_SECRET_KEY']);}
$remaining=(int)$db->query("SELECT (SELECT COUNT(*) FROM usuarios WHERE nome LIKE ".$db->quote($prefix.'%').")+(SELECT COUNT(*) FROM clientes WHERE nome LIKE ".$db->quote($prefix.'%').")+(SELECT COUNT(*) FROM aparelhos WHERE estado_fisico LIKE ".$db->quote($prefix.'%').")+(SELECT COUNT(*) FROM ordens_servico WHERE problema_relatado LIKE ".$db->quote($prefix.'%').")")->fetchColumn();$ok($remaining===0,'fixtures restantes');if($fail){fwrite(STDERR,"DeviceSecretHttpTest falhou:\n- ".implode("\n- ",$fail).PHP_EOL);exit(1);}echo "DeviceSecretHttpTest: OK (HTTP, permissoes e limpeza)\n";
